<?xml version='1.0' encoding='us-ascii'?>

      <!DOCTYPE RuleSetCollection [

      <!ELEMENT RuleSetCollection   (RuleSet*)>
      <!ATTLIST RuleSetCollection dtdVersion CDATA #IMPLIED>

      <!ELEMENT RuleSet   (Description*, Attributes*, IPInterface*, Route*, Group*, NATRule*, AccessList*)>
      <!ATTLIST RuleSet name CDATA #REQUIRED>
      <!ATTLIST RuleSet id CDATA #REQUIRED>
      <!ATTLIST RuleSet deviceType (router | firewall | switch) #REQUIRED>

      <!ELEMENT Attributes EMPTY>
      <!ATTLIST Attributes vendor CDATA #REQUIRED>
      <!ATTLIST Attributes model CDATA #IMPLIED>
      <!ATTLIST Attributes cisco.sameSecurityLevelIntraTrafficAllowed (true | false) #IMPLIED>
      <!ATTLIST Attributes cisco.sameSecurityLevelInterTrafficAllowed (true | false) #IMPLIED>
      <!ATTLIST Attributes cisco.outboundVPNBypassAcls (true | false) #IMPLIED>
      <!ATTLIST Attributes cisco.inboundVPNBypassAcls (true | false) #IMPLIED>
      <!ATTLIST Attributes fortinet.multicastBypassAcls (true | false) #IMPLIED>

      <!ELEMENT IPInterface (Description*)>
      <!ATTLIST IPInterface name CDATA #REQUIRED>
      <!ATTLIST IPInterface address CDATA #REQUIRED>
      <!ATTLIST IPInterface netmask CDATA #REQUIRED>
      <!ATTLIST IPInterface interface_type CDATA #REQUIRED>
      <!ATTLIST IPInterface interface_state CDATA #REQUIRED>
      <!ATTLIST IPInterface port_code CDATA #IMPLIED>
      <!ATTLIST IPInterface tunnel_source_interface CDATA #IMPLIED>
      <!ATTLIST IPInterface tunnel_nhrp_network_id CDATA #IMPLIED>
      <!ATTLIST IPInterface tunnel_nhs_ip CDATA #IMPLIED>      
      <!ATTLIST IPInterface ip_start CDATA #IMPLIED>
      <!ATTLIST IPInterface ip_end CDATA #IMPLIED>
      <!ATTLIST IPInterface cisco.bridge-group CDATA #IMPLIED>
      <!ATTLIST IPInterface cisco.security-level CDATA #IMPLIED>
      <!ATTLIST IPInterface vlanAccess CDATA  #IMPLIED>
      <!ATTLIST IPInterface vlanId CDATA #IMPLIED>

      <!ELEMENT Route (Description*, AddressBlock)>
      <!ATTLIST Route interfaceName CDATA #REQUIRED>
      <!ATTLIST Route gateway CDATA #REQUIRED>
      <!ATTLIST Route distance CDATA #REQUIRED>
      <!ATTLIST Route type (standard|tunneled) #IMPLIED>

      <!ELEMENT AddressBlock EMPTY>
      <!ATTLIST AddressBlock netAddress CDATA #REQUIRED>
      <!ATTLIST AddressBlock netMask CDATA #REQUIRED>

      <!ELEMENT Group (Description*, GroupElement+)>
      <!ATTLIST Group name CDATA #REQUIRED>
      <!ATTLIST Group type (ADDRESS|SERVICE|INTERFACE|USER|BINDING|PORT|PROTOCOL) #REQUIRED>

      <!ELEMENT GroupElement (Argument*)>
      <!ATTLIST GroupElement name CDATA #IMPLIED>
      <!ATTLIST GroupElement operator (WILDCARD|RANGE|GROUP|EXCEPT|LT|LTE|GT|GTE|EQ|NEQ|EMPTY) #REQUIRED>
      <!ATTLIST GroupElement type (DESCRIPTION|SERVICE|ICMPTYPE|IPADDRESS|SLICE|PORT|PROTOCOL|USER|GROUP|DYNAMIC|BINDING|INTERFACE) #IMPLIED>
      <!ELEMENT Argument ANY>

      <!ELEMENT AccessList (Description*, Rule*)>
      <!ATTLIST AccessList name CDATA #REQUIRED>
      <!ATTLIST AccessList type CDATA #IMPLIED>
      <!ATTLIST AccessList peer CDATA #IMPLIED>
      <!ATTLIST AccessList collapse CDATA #REQUIRED>

      <!ELEMENT Rule (Description*)>
      <!ATTLIST Rule name CDATA #REQUIRED>
      <!ATTLIST Rule binding_group CDATA #REQUIRED>
      <!ATTLIST Rule sequence CDATA #REQUIRED>
      <!ATTLIST Rule action (permit|deny) #REQUIRED>
      <!ATTLIST Rule enabled (true|false) #REQUIRED>
      <!ATTLIST Rule type (regular|vpn|nat|aaa|route_map) #REQUIRED>
      <!ATTLIST Rule original_lines CDATA #REQUIRED>
      <!ATTLIST Rule direction (in|out|both) #REQUIRED>
      <!ATTLIST Rule source_group CDATA #REQUIRED>
      <!ATTLIST Rule destination_group CDATA #REQUIRED>
      <!ATTLIST Rule service_group CDATA #REQUIRED>
      <!ATTLIST Rule user_group CDATA #IMPLIED>

      <!ELEMENT NATRule (NATMatch+,NATPool+)>
      <!ATTLIST NATRule id CDATA #REQUIRED>
      <!ATTLIST NATRule coupled CDATA #IMPLIED>
      <!ATTLIST NATRule inside_interface CDATA #REQUIRED>
      <!ATTLIST NATRule outside_interface CDATA #REQUIRED>
      <!ATTLIST NATRule direction (in|out|both) #REQUIRED>
      <!ATTLIST NATRule side (src|dst|either) #REQUIRED>
      <!ATTLIST NATRule other CDATA #IMPLIED>
      <!ATTLIST NATRule applyUsingRule CDATA #IMPLIED>

      <!ELEMENT NATMatch EMPTY>
      <!ATTLIST NATMatch ipMatch CDATA #REQUIRED>
      <!ATTLIST NATMatch portMatch CDATA #IMPLIED>

      <!ELEMENT NATPool EMPTY>
      <!ATTLIST NATPool ipPool CDATA #REQUIRED>
      <!ATTLIST NATPool portPool CDATA #IMPLIED>

      <!ELEMENT Description (#PCDATA)>
      ]>
    
<RuleSetCollection
 dtdVersion="1.5.25">
    <RuleSet
     deviceType="firewall"
     id="1445"
     name="Paris">
        <Description>Paris
        </Description>
        <Attributes
         cisco.inboundVPNBypassAcls="true"
         cisco.outboundVPNBypassAcls="true"
         model="8.2(1)3"
         vendor="cisco" />
        <IPInterface
         address="10.1.1.5"
         cisco.security-level="0"
         interface_state="active"
         interface_type="standard"
         name="outside"
         netmask="255.255.255.0"
         port_code="Ethernet0/0" />
        <IPInterface
         address="10.35.1.1"
         cisco.security-level="100"
         interface_state="active"
         interface_type="standard"
         name="inside"
         netmask="255.255.255.0"
         port_code="Ethernet0/1" />
        <IPInterface
         address="unknown"
         cisco.security-level="-1"
         interface_state="shutdown"
         interface_type="standard"
         name="Ethernet0/2"
         netmask=""
         port_code="Ethernet0/2" />
        <IPInterface
         address="unknown"
         cisco.security-level="-1"
         interface_state="shutdown"
         interface_type="standard"
         name="Ethernet0/3"
         netmask=""
         port_code="Ethernet0/3" />
        <IPInterface
         address="unknown"
         cisco.security-level="-1"
         interface_state="active"
         interface_type="standard"
         name="Management0/0"
         netmask=""
         port_code="Management0/0" />
        <IPInterface
         address="unknown"
         cisco.security-level="-1"
         interface_state="shutdown"
         interface_type="standard"
         name="GigabitEthernet1/0"
         netmask=""
         port_code="GigabitEthernet1/0" />
        <IPInterface
         address="unknown"
         cisco.security-level="-1"
         interface_state="shutdown"
         interface_type="standard"
         name="GigabitEthernet1/1"
         netmask=""
         port_code="GigabitEthernet1/1" />
        <IPInterface
         address="unknown"
         cisco.security-level="-1"
         interface_state="shutdown"
         interface_type="standard"
         name="GigabitEthernet1/2"
         netmask=""
         port_code="GigabitEthernet1/2" />
        <IPInterface
         address="unknown"
         cisco.security-level="-1"
         interface_state="shutdown"
         interface_type="standard"
         name="GigabitEthernet1/3"
         netmask=""
         port_code="GigabitEthernet1/3" />
        <Route
         distance="1"
         gateway="10.1.1.1"
         interfaceName="outside"
         type="standard">
            <AddressBlock
             netAddress="0.0.0.0"
             netMask="255.255.255.255" />
        </Route>
        <Group
         name="NPV_IFACE_NONE"
         type="BINDING">
            <Description>No interface
            </Description>
            <GroupElement
             operator="EMPTY"
             type="BINDING" />
        </Group>
        <Group
         name="NPV_GROUP_1444"
         type="BINDING">
            <GroupElement
             operator="EQ"
             type="BINDING">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="INTERFACE">
                        <Argument>outside
                        </Argument>
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="INTERFACE">
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_IFACE_ANY"
         type="BINDING">
            <Description>Any interface
            </Description>
            <GroupElement
             operator="EQ"
             type="BINDING">
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="INTERFACE">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="INTERFACE">
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_GROUP_1441"
         type="BINDING">
            <GroupElement
             operator="EQ"
             type="BINDING">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="INTERFACE">
                        <Argument>inside
                        </Argument>
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="INTERFACE">
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_SVC_ANY"
         type="SERVICE">
            <Description>Any port and protocol
            </Description>
            <GroupElement
             operator="WILDCARD"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PROTOCOL">
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="HTTP"
         type="SERVICE">
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>80
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>443
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_GROUP_1430"
         type="SERVICE">
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>22
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="ICCP_DATA"
         type="SERVICE">
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>102
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>8080
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_GROUP_1435"
         type="SERVICE">
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>4
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_GROUP_1402"
         type="SERVICE">
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>4
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_GROUP_1416"
         type="SERVICE">
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>22
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="FTP_DATA"
         type="SERVICE">
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>20
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>21
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>2049
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="SCADA"
         type="SERVICE">
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>7000
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="SERVICE">
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PROTOCOL">
                        <Argument>6
                        </Argument>
                        <Argument>#PROTO#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="WILDCARD"
                     type="PORT">
                        <Argument>#SRC#
                        </Argument>
                    </GroupElement>
                </Argument>
                <Argument>
                    <GroupElement
                     operator="EQ"
                     type="PORT">
                        <Argument>80
                        </Argument>
                        <Argument>#DST#
                        </Argument>
                    </GroupElement>
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_ADDR_ANY"
         type="ADDRESS">
            <Description>Any address
            </Description>
            <GroupElement
             operator="WILDCARD"
             type="IPADDRESS" />
        </Group>
        <Group
         name="EMS_SERVERS"
         type="ADDRESS">
            <GroupElement
             operator="EQ"
             type="IPADDRESS">
                <Argument>72.36.82.195
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="DIST"
         type="ADDRESS">
            <GroupElement
             operator="EQ"
             type="GROUP">
                <Argument>PARIS
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="GROUP">
                <Argument>PARIS_451
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="GROUP">
                <Argument>PARIS_421
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="JUMP_HOST"
         type="ADDRESS">
            <GroupElement
             operator="EQ"
             type="IPADDRESS">
                <Argument>10.39.1.22
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="PARIS_451"
         type="ADDRESS">
            <GroupElement
             operator="EQ"
             type="IPADDRESS">
                <Argument>10.35.1.101
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="IPADDRESS">
                <Argument>10.35.1.102
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="IPADDRESS">
                <Argument>10.35.1.103
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="IPADDRESS">
                <Argument>10.35.1.104
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="PEER_UTILS"
         type="ADDRESS">
            <GroupElement
             operator="EQ"
             type="IPADDRESS">
                <Argument>192.17.102.102
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="IPADDRESS">
                <Argument>192.17.102.103
                </Argument>
            </GroupElement>
            <GroupElement
             operator="EQ"
             type="IPADDRESS">
                <Argument>192.17.102.104
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_GROUP_1424"
         type="ADDRESS">
            <GroupElement
             operator="EQ"
             type="GROUP">
                <Argument>DIST
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_GROUP_1423"
         type="ADDRESS">
            <GroupElement
             operator="EQ"
             type="GROUP">
                <Argument>EMS_SERVERS
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_GROUP_1403"
         type="ADDRESS">
            <GroupElement
             operator="WILDCARD"
             type="IPADDRESS" />
        </Group>
        <Group
         name="EMS_FEP"
         type="ADDRESS">
            <GroupElement
             operator="EQ"
             type="IPADDRESS">
                <Argument>72.36.82.194
                </Argument>
            </GroupElement>
        </Group>
        <Group
         name="NPV_GROUP_1404"
         type="ADDRESS">
            <GroupElement
             operator="WILDCARD"
             type="IPADDRESS" />
        </Group>
        <Group
         name="NPV_GROUP_1409"
         type="ADDRESS">
            <GroupElement
             operator="EQ"
             type="GROUP">
                <Argument>PEER_UTILS
                </Argument>
            </GroupElement>
        </Group>
        <Group