<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Topology [ 
<!ELEMENT Topology (Network*, Device*, Tunnel*)>
<!ATTLIST Topology dtdVersion CDATA #IMPLIED>

<!ELEMENT Network (Description*)>
<!ATTLIST Network name CDATA #REQUIRED>
<!ATTLIST Network aliases CDATA #IMPLIED>
<!ATTLIST Network id CDATA #REQUIRED>
<!ATTLIST Network parentId CDATA #IMPLIED>
<!ATTLIST Network netAddress CDATA #REQUIRED>
<!ATTLIST Network netMask CDATA #REQUIRED>
<!ATTLIST Network critical (true|false) #REQUIRED>
<!ATTLIST Network network_type CDATA #REQUIRED>
<!ATTLIST Network tunnel_network_hub_node_id CDATA #REQUIRED>
<!ATTLIST Network cloud (true|false) #REQUIRED>
<!ATTLIST Network hidden (true|false) #IMPLIED>
<!ATTLIST Network nodeRefId CDATA #IMPLIED>
<!ATTLIST Network rooted (src|dst|both) #IMPLIED>
<!ATTLIST Network group CDATA #IMPLIED>

<!ELEMENT Device (Description*, DNSServer*, NIC*,Service*)>
<!ATTLIST Device name CDATA #REQUIRED>
<!ATTLIST Device aliases CDATA #IMPLIED>
<!ATTLIST Device id CDATA #REQUIRED>
<!ATTLIST Device type (firewall|router|host|gateway|range|cluster|host_router) #REQUIRED>
<!ATTLIST Device members CDATA #IMPLIED>
<!ATTLIST Device pseudo (true|false) #IMPLIED>
<!ATTLIST Device hidden (true|false) #IMPLIED>
<!ATTLIST Device nodeRefId CDATA #IMPLIED>
<!ATTLIST Device rooted (src|dst|both) #IMPLIED>
<!ATTLIST Device group CDATA #IMPLIED>
<!ATTLIST Device status CDATA #IMPLIED>
<!ATTLIST Device oses CDATA #IMPLIED>

<!ELEMENT NIC EMPTY>
<!ATTLIST NIC name CDATA #IMPLIED>
<!ATTLIST NIC ipAddress CDATA #REQUIRED>
<!ATTLIST NIC nodeRefId CDATA #IMPLIED>

<!ELEMENT Service (Vulnerability*)>
<!ATTLIST Service name CDATA #REQUIRED>
<!ATTLIST Service product CDATA #IMPLIED>
<!ATTLIST Service version CDATA #IMPLIED>
<!ATTLIST Service protocol CDATA #REQUIRED>
<!ATTLIST Service port CDATA #REQUIRED>

<!ELEMENT Vulnerability EMPTY>
<!ATTLIST Vulnerability id CDATA #REQUIRED>
<!ATTLIST Vulnerability cvssVector CDATA #IMPLIED>
<!ATTLIST Vulnerability cvssBaseScore CDATA #IMPLIED>
<!ATTLIST Vulnerability cvssExploitSubScore CDATA #IMPLIED>
<!ATTLIST Vulnerability cvssImpactSubScore CDATA #IMPLIED>

<!ELEMENT Tunnel (Description*)>
<!ATTLIST Tunnel encryption (none|ipsec|ssl|l2tp|pptp) #IMPLIED>
<!ATTLIST Tunnel id CDATA #REQUIRED>
<!ATTLIST Tunnel dialup (true|false) #IMPLIED>
<!ATTLIST Tunnel endpoint_1 CDATA #REQUIRED>
<!ATTLIST Tunnel interface_1 CDATA #REQUIRED>
<!ATTLIST Tunnel address_1 CDATA #REQUIRED>
<!ATTLIST Tunnel endpoint_2 CDATA #REQUIRED>
<!ATTLIST Tunnel interface_2 CDATA #REQUIRED>
<!ATTLIST Tunnel address_2 CDATA #REQUIRED>
<!ATTLIST Tunnel name CDATA #IMPLIED>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT DNSServer (#PCDATA)>
]>

<Topology
 dtdVersion="1.5.20">
    <Network
     aliases="inside"
     cloud="false"
     critical="false"
     hidden="false"
     id="1878"
     name="10.32.1.0/24"
     netAddress="10.32.1.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Network
     aliases="outside"
     cloud="false"
     critical="false"
     hidden="false"
     id="1875"
     name="72.36.82.0/24"
     netAddress="72.36.82.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Network
     aliases="inside"
     cloud="false"
     critical="false"
     hidden="false"
     id="1877"
     name="10.31.1.0/24"
     netAddress="10.31.1.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Network
     aliases="inside"
     cloud="false"
     critical="false"
     hidden="false"
     id="1871"
     name="10.34.1.0/24"
     netAddress="10.34.1.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Network
     aliases="inside"
     cloud="false"
     critical="false"
     hidden="false"
     id="1873"
     name="10.36.1.0/24"
     netAddress="10.36.1.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Network
     aliases="inside"
     cloud="false"
     critical="false"
     hidden="false"
     id="1872"
     name="10.35.1.0/24"
     netAddress="10.35.1.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Network
     aliases="outside"
     cloud="false"
     critical="false"
     hidden="false"
     id="1868"
     name="10.1.1.0/24"
     netAddress="10.1.1.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Network
     aliases="inside"
     cloud="false"
     critical="false"
     hidden="false"
     id="1869"
     name="10.37.1.0/24"
     netAddress="10.37.1.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Network
     cloud="false"
     critical="false"
     hidden="true"
     id="2029"
     name="72.0.0.0/8"
     netAddress="72.0.0.0"
     netMask="255.0.0.0"
     network_type="standard"
     nodeRefId="2028"
     rooted="dst"
     tunnel_network_hub_node_id="None" />
    <Network
     aliases="inside"
     cloud="false"
     critical="false"
     hidden="false"
     id="1870"
     name="10.33.1.0/24"
     netAddress="10.33.1.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Network
     cloud="false"
     critical="false"
     hidden="true"
     id="1881"
     name="Internet"
     netAddress="0.0.0.0"
     netMask="0.0.0.0"
     network_type="standard"
     nodeRefId="1880"
     tunnel_network_hub_node_id="None" />
    <Network
     cloud="false"
     critical="false"
     hidden="true"
     id="1882"
     name="unmapped"
     netAddress="0.0.0.0"
     netMask="0.0.0.0"
     network_type="standard"
     nodeRefId="1880"
     tunnel_network_hub_node_id="None" />
    <Network
     aliases="inside"
     cloud="false"
     critical="false"
     hidden="false"
     id="1874"
     name="10.38.1.0/24"
     netAddress="10.38.1.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Network
     cloud="false"
     critical="false"
     hidden="true"
     id="2030"
     name="192.17.0.0/16"
     netAddress="192.17.0.0"
     netMask="255.255.0.0"
     network_type="standard"
     nodeRefId="2028"
     rooted="dst"
     tunnel_network_hub_node_id="None" />
    <Network
     aliases="dmz"
     cloud="false"
     critical="false"
     hidden="false"
     id="1876"
     name="10.39.1.0/24"
     netAddress="10.39.1.0"
     netMask="255.255.255.0"
     network_type="standard"
     tunnel_network_hub_node_id="None" />
    <Device
     hidden="false"
     id="1920"
     name="10.33.1.103"
     pseudo="false"
     type="host">
        <Description>10.33.1.103
        </Description>
        <NIC
         ipAddress="10.33.1.103"
         name="NPV_IFACE_1919"
         nodeRefId="1870" />
    </Device>
    <Device
     hidden="false"
     id="1922"
     name="10.33.1.104"
     pseudo="false"
     type="host">
        <Description>10.33.1.104
        </Description>
        <NIC
         ipAddress="10.33.1.104"
         name="NPV_IFACE_1921"
         nodeRefId="1870" />
    </Device>
    <Device
     hidden="false"
     id="1924"
     name="10.33.1.105"
     pseudo="false"
     type="host">
        <Description>10.33.1.105
        </Description>
        <NIC
         ipAddress="10.33.1.105"
         name="NPV_IFACE_1923"
         nodeRefId="1870" />
    </Device>
    <Device
     hidden="false"
     id="1926"
     name="10.33.1.106"
     pseudo="false"
     type="host">
        <Description>10.33.1.106
        </Description>
        <NIC
         ipAddress="10.33.1.106"
         name="NPV_IFACE_1925"
         nodeRefId="1870" />
    </Device>
    <Device
     hidden="false"
     id="1928"
     name="10.33.1.107"
     pseudo="false"
     type="host">
        <Description>10.33.1.107
        </Description>
        <NIC
         ipAddress="10.33.1.107"
         name="NPV_IFACE_1927"
         nodeRefId="1870" />
    </Device>
    <Device
     aliases="NORTHHAVERBROOK"
     hidden="false"
     id="1930"
     name="10.33.1.250"
     pseudo="false"
     type="host">
        <Description>10.33.1.250
        </Description>
        <NIC
         ipAddress="10.33.1.250"
         name="NPV_IFACE_1929"
         nodeRefId="1870" />
    </Device>
    <Device
     aliases="OGDENVILLE"
     hidden="false"
     id="1932"
     name="10.34.1.250"
     pseudo="false"
     type="host">
        <Description>10.34.1.250
        </Description>
        <NIC
         ipAddress="10.34.1.250"
         name="NPV_IFACE_1931"
         nodeRefId="1871" />
    </Device>
    <Device
     hidden="false"
     id="1934"
     name="10.34.1.201"
     pseudo="false"
     type="host">
        <Description>10.34.1.201
        </Description>
        <NIC
         ipAddress="10.34.1.201"
         name="NPV_IFACE_1933"
         nodeRefId="1871" />
    </Device>
    <Device
     hidden="false"
     id="1936"
     name="10.34.1.202"
     pseudo="false"
     type="host">
        <Description>10.34.1.202
        </Description>
        <NIC
         ipAddress="10.34.1.202"
         name="NPV_IFACE_1935"
         nodeRefId="1871" />
    </Device>
    <Device
     hidden="false"
     id="1938"
     name="10.34.1.101"
     pseudo="false"
     type="host">
        <Description>10.34.1.101
        </Description>
        <NIC
         ipAddress="10.34.1.101"
         name="NPV_IFACE_1937"
         nodeRefId="1871" />
    </Device>
    <Device
     hidden="false"
     id="1940"
     name="10.34.1.102"
     pseudo="false"
     type="host">
        <Description>10.34.1.102
        </Description>
        <NIC
         ipAddress="10.34.1.102"
         name="NPV_IFACE_1939"
         nodeRefId="1871" />
    </Device>
    <Device
     hidden="false"
     id="1942"
     name="10.34.1.103"
     pseudo="false"
     type="host">
        <Description>10.34.1.103
        </Description>
        <NIC
         ipAddress="10.34.1.103"
         name="NPV_IFACE_1941"
         nodeRefId="1871" />
    </Device>
    <Device
     aliases="PARIS"
     hidden="false"
     id="1944"
     name="10.35.1.250"
     pseudo="false"
     type="host">
        <Description>10.35.1.250
        </Description>
        <NIC
         ipAddress="10.35.1.250"
         name="NPV_IFACE_1943"
         nodeRefId="1872" />
    </Device>
    <Device
     hidden="false"
     id="1946"
     name="10.35.1.201"
     pseudo="false"
     type="host">
        <Description>10.35.1.201
        </Description>
        <NIC
         ipAddress="10.35.1.201"
         name="NPV_IFACE_1945"
         nodeRefId="1872" />
    </Device>
    <Device
     hidden="false"
     id="1948"
     name="10.35.1.202"
     pseudo="false"
     type="host">
        <Description>10.35.1.202
        </Description>
        <NIC
         ipAddress="10.35.1.202"
         name="NPV_IFACE_1947"
         nodeRefId="1872" />
    </Device>
    <Device
     hidden="false"
     id="1950"
     name="10.35.1.203"
     pseudo="false"
     type="host">
        <Description>10.35.1.203
        </Description>
        <NIC
         ipAddress="10.35.1.203"
         name="NPV_IFACE_1949"
         nodeRefId="1872" />
    </Device>
    <Device
     hidden="false"
     id="1952"
     name="10.35.1.101"
     pseudo="false"
     type="host">
        <Description>10.35.1.101
        </Description>
        <NIC
         ipAddress="10.35.1.101"
         name="NPV_IFACE_1951"
         nodeRefId="1872" />
    </Device>
    <Device
     hidden="false"
     id="1954"
     name="10.35.1.102"
     pseudo="false"
     type="host">
        <Description>10.35.1.102
        </Description>
        <NIC
         ipAddress="10.35.1.102"
         name="NPV_IFACE_1953"
         nodeRefId="1872" />
    </Device>
    <Device
     hidden="false"
     id="1956"
     name="10.35.1.103"
     pseudo="false"
     type="host">
        <Description>10.35.1.103
        </Description>
        <NIC
         ipAddress="10.35.1.103"
         name="NPV_IFACE_1955"
         nodeRefId="1872" />
    </Device>
    <Device
     hidden="false"
     id="1958"
     name="10.35.1.104"
     pseudo="false"
     type="host">
        <Description>10.35.1.104
        </Description>
        <NIC
         ipAddress="10.35.1.104"
         name="NPV_IFACE_1957"
         nodeRefId="1872" />
    </Device>
    <Device
     aliases="SHELBYVILLE"
     hidden="false"
     id="1960"
     name="10.36.1.250"
     pseudo="false"
     type="host">
        <Description>10.36.1.250
        </Description>
        <NIC
         ipAddress="10.36.1.250"
         name="NPV_IFACE_1959"
         nodeRefId="1873" />
    </Device>
    <Device
     hidden="false"
     id="2012"
     name="10.31.1.101"
     pseudo="false"
     status="up"
     type="host">
        <Description>10.31.1.101
        </Description>
        <NIC
         ipAddress="10.31.1.101"
         name="NPV_IFACE_2011"
         nodeRefId="1877" />
        <Service
         name="ssh"
         port="22"
         product="ssh"
         protocol="tcp"
         version="">
            <Vulnerability
             cvssBaseScore="4.95845112"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:N,C:N,I:N,A:P)"
             id="CVE-2015-7845" />
            <Vulnerability
             cvssBaseScore="9.99509120602"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:N,C:C,I:C,A:C)"
             id="CVE-2015-6476" />
            <Vulnerability
             cvssBaseScore="6.52278517275"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="6.44297671875"
             cvssVector="(AV:N,AC:L,Au:S,C:P,I:P,A:P)"
             id="CVE-2015-6316" />
            <Vulnerability
             cvssBaseScore="7.78639008"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="6.8706"
             cvssVector="(AV:N,AC:L,Au:N,C:N,I:N,A:C)"
             id="CVE-2015-7752" />
            <Vulnerability
             cvssBaseScore="7.48465909275"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="6.44297671875"
             cvssVector="(AV:L,AC:L,Au:N,C:P,I:P,A:P)"
             id="CVE-2015-6333" />
            <Vulnerability
             cvssBaseScore="4.95845112"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:N,C:N,I:N,A:P)"
             id="CVE-2015-7760" />
            <Vulnerability
             cvssBaseScore="3.9965772"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:S,C:N,I:N,A:P)"
             id="CVE-2015-6300" />
            <Vulnerability
             cvssBaseScore="4.29612792"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:L,AC:M,Au:N,C:N,I:P,A:N)"
             id="CVE-2015-6563" />
            <Vulnerability
             cvssBaseScore="9.03321728602"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:S,C:C,I:C,A:C)"
             id="CVE-2015-2907" />
            <Vulnerability
             cvssBaseScore="9.03321728602"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:S,C:C,I:C,A:C)"
             id="CVE-2015-2906" />
            <Vulnerability
             cvssBaseScore="9.99509120602"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:N,C:C,I:C,A:C)"
             id="CVE-2015-2897" />
            <Vulnerability
             cvssBaseScore="8.473175256"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="7.843935"
             cvssVector="(AV:N,AC:L,Au:N,C:P,I:N,A:C)"
             id="CVE-2015-5600" />
            <Vulnerability
             cvssBaseScore="4.29612792"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:M,Au:N,C:N,I:P,A:N)"
             id="CVE-2015-5352" />
            <Vulnerability
             cvssBaseScore="4.29612792"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:M,Au:N,C:N,I:N,A:P)"
             id="CVE-2015-4236" />
            <Vulnerability
             cvssBaseScore="4.95845112"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:N,C:P,I:N,A:N)"
             id="CVE-2015-4196" />
            <Vulnerability
             cvssBaseScore="4.29612792"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:M,Au:N,C:P,I:N,A:N)"
             id="CVE-2015-4217" />
            <Vulnerability
             cvssBaseScore="4.95845112"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:N,C:P,I:N,A:N)"
             id="CVE-2015-4216" />
            <Vulnerability
             cvssBaseScore="3.9965772"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:S,C:N,I:N,A:P)"
             id="CVE-2015-4195" />
            <Vulnerability
             cvssBaseScore="8.7723513024"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="9.206604"
             cvssVector="(AV:N,AC:M,Au:N,C:C,I:C,A:N)"
             id="CVE-2012-4716" />
        </Service>
    </Device>
    <Device
     hidden="false"
     id="1962"
     name="10.36.1.201"
     pseudo="false"
     type="host">
        <Description>10.36.1.201
        </Description>
        <NIC
         ipAddress="10.36.1.201"
         name="NPV_IFACE_1961"
         nodeRefId="1873" />
    </Device>
    <Device
     hidden="false"
     id="1964"
     name="10.36.1.202"
     pseudo="false"
     type="host">
        <Description>10.36.1.202
        </Description>
        <NIC
         ipAddress="10.36.1.202"
         name="NPV_IFACE_1963"
         nodeRefId="1873" />
    </Device>
    <Device
     hidden="false"
     id="1966"
     name="10.36.1.203"
     pseudo="false"
     type="host">
        <Description>10.36.1.203
        </Description>
        <NIC
         ipAddress="10.36.1.203"
         name="NPV_IFACE_1965"
         nodeRefId="1873" />
    </Device>
    <Device
     hidden="false"
     id="1968"
     name="10.36.1.101"
     pseudo="false"
     type="host">
        <Description>10.36.1.101
        </Description>
        <NIC
         ipAddress="10.36.1.101"
         name="NPV_IFACE_1967"
         nodeRefId="1873" />
    </Device>
    <Device
     hidden="false"
     id="1970"
     name="10.36.1.102"
     pseudo="false"
     type="host">
        <Description>10.36.1.102
        </Description>
        <NIC
         ipAddress="10.36.1.102"
         name="NPV_IFACE_1969"
         nodeRefId="1873" />
    </Device>
    <Device
     hidden="false"
     id="1972"
     name="10.36.1.103"
     pseudo="false"
     type="host">
        <Description>10.36.1.103
        </Description>
        <NIC
         ipAddress="10.36.1.103"
         name="NPV_IFACE_1971"
         nodeRefId="1873" />
    </Device>
    <Device
     hidden="false"
     id="2014"
     name="10.31.1.102"
     pseudo="false"
     status="up"
     type="host">
        <Description>10.31.1.102
        </Description>
        <NIC
         ipAddress="10.31.1.102"
         name="NPV_IFACE_2013"
         nodeRefId="1877" />
        <Service
         name="ssh"
         port="22"
         product="ssh"
         protocol="tcp"
         version="">
            <Vulnerability
             cvssBaseScore="4.95845112"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:N,C:N,I:N,A:P)"
             id="CVE-2015-7845" />
            <Vulnerability
             cvssBaseScore="9.99509120602"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:N,C:C,I:C,A:C)"
             id="CVE-2015-6476" />
            <Vulnerability
             cvssBaseScore="6.52278517275"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="6.44297671875"
             cvssVector="(AV:N,AC:L,Au:S,C:P,I:P,A:P)"
             id="CVE-2015-6316" />
            <Vulnerability
             cvssBaseScore="7.78639008"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="6.8706"
             cvssVector="(AV:N,AC:L,Au:N,C:N,I:N,A:C)"
             id="CVE-2015-7752" />
            <Vulnerability
             cvssBaseScore="7.48465909275"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="6.44297671875"
             cvssVector="(AV:L,AC:L,Au:N,C:P,I:P,A:P)"
             id="CVE-2015-6333" />
            <Vulnerability
             cvssBaseScore="4.95845112"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:N,C:N,I:N,A:P)"
             id="CVE-2015-7760" />
            <Vulnerability
             cvssBaseScore="3.9965772"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:S,C:N,I:N,A:P)"
             id="CVE-2015-6300" />
            <Vulnerability
             cvssBaseScore="4.29612792"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:L,AC:M,Au:N,C:N,I:P,A:N)"
             id="CVE-2015-6563" />
            <Vulnerability
             cvssBaseScore="9.03321728602"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:S,C:C,I:C,A:C)"
             id="CVE-2015-2907" />
            <Vulnerability
             cvssBaseScore="9.03321728602"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:S,C:C,I:C,A:C)"
             id="CVE-2015-2906" />
            <Vulnerability
             cvssBaseScore="9.99509120602"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:N,C:C,I:C,A:C)"
             id="CVE-2015-2897" />
            <Vulnerability
             cvssBaseScore="8.473175256"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="7.843935"
             cvssVector="(AV:N,AC:L,Au:N,C:P,I:N,A:C)"
             id="CVE-2015-5600" />
            <Vulnerability
             cvssBaseScore="4.29612792"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:M,Au:N,C:N,I:P,A:N)"
             id="CVE-2015-5352" />
            <Vulnerability
             cvssBaseScore="4.29612792"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:M,Au:N,C:N,I:N,A:P)"
             id="CVE-2015-4236" />
            <Vulnerability
             cvssBaseScore="4.95845112"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:N,C:P,I:N,A:N)"
             id="CVE-2015-4196" />
            <Vulnerability
             cvssBaseScore="4.29612792"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:M,Au:N,C:P,I:N,A:N)"
             id="CVE-2015-4217" />
            <Vulnerability
             cvssBaseScore="4.95845112"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:N,C:P,I:N,A:N)"
             id="CVE-2015-4216" />
            <Vulnerability
             cvssBaseScore="3.9965772"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:S,C:N,I:N,A:P)"
             id="CVE-2015-4195" />
            <Vulnerability
             cvssBaseScore="8.7723513024"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="9.206604"
             cvssVector="(AV:N,AC:M,Au:N,C:C,I:C,A:N)"
             id="CVE-2012-4716" />
        </Service>
    </Device>
    <Device
     hidden="false"
     id="1974"
     name="10.36.1.104"
     pseudo="false"
     type="host">
        <Description>10.36.1.104
        </Description>
        <NIC
         ipAddress="10.36.1.104"
         name="NPV_IFACE_1973"
         nodeRefId="1873" />
    </Device>
    <Device
     hidden="false"
     id="1976"
     name="10.36.1.105"
     pseudo="false"
     type="host">
        <Description>10.36.1.105
        </Description>
        <NIC
         ipAddress="10.36.1.105"
         name="NPV_IFACE_1975"
         nodeRefId="1873" />
    </Device>
    <Device
     hidden="false"
     id="1978"
     name="10.38.1.201"
     pseudo="false"
     type="host">
        <Description>10.38.1.201
        </Description>
        <NIC
         ipAddress="10.38.1.201"
         name="NPV_IFACE_1977"
         nodeRefId="1874" />
    </Device>
    <Device
     hidden="false"
     id="1980"
     name="10.38.1.202"
     pseudo="false"
     type="host">
        <Description>10.38.1.202
        </Description>
        <NIC
         ipAddress="10.38.1.202"
         name="NPV_IFACE_1979"
         nodeRefId="1874" />
    </Device>
    <Device
     hidden="false"
     id="1982"
     name="10.38.1.203"
     pseudo="false"
     type="host">
        <Description>10.38.1.203
        </Description>
        <NIC
         ipAddress="10.38.1.203"
         name="NPV_IFACE_1981"
         nodeRefId="1874" />
    </Device>
    <Device
     hidden="false"
     id="1984"
     name="10.38.1.101"
     pseudo="false"
     type="host">
        <Description>10.38.1.101
        </Description>
        <NIC
         ipAddress="10.38.1.101"
         name="NPV_IFACE_1983"
         nodeRefId="1874" />
    </Device>
    <Device
     hidden="false"
     id="2016"
     name="10.31.1.103"
     pseudo="false"
     status="up"
     type="host">
        <Description>10.31.1.103
        </Description>
        <NIC
         ipAddress="10.31.1.103"
         name="NPV_IFACE_2015"
         nodeRefId="1877" />
        <Service
         name="ssh"
         port="22"
         product="ssh"
         protocol="tcp"
         version="">
            <Vulnerability
             cvssBaseScore="4.95845112"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:N,C:N,I:N,A:P)"
             id="CVE-2015-7845" />
            <Vulnerability
             cvssBaseScore="9.99509120602"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:N,C:C,I:C,A:C)"
             id="CVE-2015-6476" />
            <Vulnerability
             cvssBaseScore="6.52278517275"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="6.44297671875"
             cvssVector="(AV:N,AC:L,Au:S,C:P,I:P,A:P)"
             id="CVE-2015-6316" />
            <Vulnerability
             cvssBaseScore="7.78639008"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="6.8706"
             cvssVector="(AV:N,AC:L,Au:N,C:N,I:N,A:C)"
             id="CVE-2015-7752" />
            <Vulnerability
             cvssBaseScore="7.48465909275"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="6.44297671875"
             cvssVector="(AV:L,AC:L,Au:N,C:P,I:P,A:P)"
             id="CVE-2015-6333" />
            <Vulnerability
             cvssBaseScore="4.95845112"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:N,C:N,I:N,A:P)"
             id="CVE-2015-7760" />
            <Vulnerability
             cvssBaseScore="3.9965772"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:L,Au:S,C:N,I:N,A:P)"
             id="CVE-2015-6300" />
            <Vulnerability
             cvssBaseScore="4.29612792"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:L,AC:M,Au:N,C:N,I:P,A:N)"
             id="CVE-2015-6563" />
            <Vulnerability
             cvssBaseScore="9.03321728602"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:S,C:C,I:C,A:C)"
             id="CVE-2015-2907" />
            <Vulnerability
             cvssBaseScore="9.03321728602"
             cvssExploitSubScore="7.952"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:S,C:C,I:C,A:C)"
             id="CVE-2015-2906" />
            <Vulnerability
             cvssBaseScore="9.99509120602"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="10.00084536"
             cvssVector="(AV:N,AC:L,Au:N,C:C,I:C,A:C)"
             id="CVE-2015-2897" />
            <Vulnerability
             cvssBaseScore="8.473175256"
             cvssExploitSubScore="9.9968"
             cvssImpactSubScore="7.843935"
             cvssVector="(AV:N,AC:L,Au:N,C:P,I:N,A:C)"
             id="CVE-2015-5600" />
            <Vulnerability
             cvssBaseScore="4.29612792"
             cvssExploitSubScore="8.5888"
             cvssImpactSubScore="2.86275"
             cvssVector="(AV:N,AC:M,Au:N,C:N,I:P,A:N)"
             id="CVE-2015-5352" />
            <Vulnerability
             cvssBaseScore="4.29612792"